item/urls.py
from django.conf.urls import url
from . import views

app_name = 'item'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rfid/$', views.listRFId, name='list_rfid'),
    url(r'^register/$', views.register, name='register'),
    url(r'^item_in/$', views.item_in, name='item_in'),
    url(r'^item_out/$', views.item_out, name='item_out'),
    url(r'^create_rfid/$', views.create_rfid, name='create_rfid'),
    url(r'^rfids_add/$', views.rfids_add, name='rfids_add'),
    url(r'^rfids_out/$', views.rfids_out, name='rfids_out'),
    url(r'^rfids_in/$', views.rfids_in, name='rfids_in'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<rfid_rf_id>[A-Z0-9]+)/$', views.detail, name='detail'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.rfiddets, name='rfiddets'),
    url(r'^(?P<rfid_rf_id>[A-Z0-9]+)/create_rfiddet/$', views.create_rfiddet, name='create_rfiddet'),
    url(r'^(?P<rfid_rf_id>[A-Z0-9]+)/delete_rfiddet/(?P<rfiddet_id>[0-9]+)/$', views.delete_rfiddet, name='delete_rfiddet'),
    url(r'^(?P<rfid_rf_id>[A-Z0-9]+)/delete_rfid/$', views.delete_rfid, name='delete_rfid'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^item/', include('item.urls')),
    url(r'^', include('item.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import date


class RFId(models.Model):
    MANUFACTURE = 'MFR'
    OUT = 'OUT'
    IN = 'IN'
    WASTE = 'WST'

    rf_id_state_CHOICES = (
        (MANUFACTURE, '제품입고'),
        (OUT, '납품'),
        (IN, '수리입고'),
        (WASTE, '폐기'),
    )

    rf_id = models.CharField(primary_key=True, max_length=10)
    mfr_date = models.DateField(db_index=True, default=date.today)
    mfr_firm = models.CharField(max_length=50, blank=True)      #제조 회사
    expire_yn = models.BooleanField(default=False)
    expire_date = models.DateField(null=True, blank=True)
    out_firm = models.CharField(max_length=50, blank=True, null=True)      #납품회사
    out_date = models.DateField(null=True, blank=True)              #납품일자
    in_date = models.DateField(null=True, blank=True)  # 입고일자(for 수리)

    rf_id_state = models.CharField(max_length=3, choices=rf_id_state_CHOICES, default='MFR')
    #rfid상태코드 : MFR[제조입고], OUT[납품],IN[수리입고],FIX[수리완료], WASTE[폐기]

    def __str__(self):
        return self.rf_id + ' - ' + self.mfr_firm

class RFIdDet(models.Model):

    RFId = models.ForeignKey(RFId, on_delete=models.CASCADE)
    out_date = models.DateField(default=date.today)              #납품일자
    in_date = models.DateField(null=True, blank=True)           #수리입고일자
    message = models.CharField(max_length=300, blank=True, null=True)          #수리의견

    def __str__(self):
        return self.RFId + ' - ' + self.out_date


class Item(models.Model):

    PRODUCT = 'PRO'
    MATERIAL = 'MAT'
    CONSUMABLE = 'CON'
    ITEM_TYPE_CHOICES = (
        (PRODUCT, '제품'),
        (MATERIAL, '자재'),
        (CONSUMABLE, '소모품'),
    )

    item_id = models.CharField(primary_key=True, max_length=10)
    item_name = models.CharField(max_length=20, blank=True, null=True, help_text="Item Name")
    item_type = models.CharField(max_length=3, choices=ITEM_TYPE_CHOICES, default='PRO')

    def __str__(self):
        return self.item_name


class ItemOut(models.Model):
    Item = models.ForeignKey(Item)
    out_date = models.DateField(default=date.today)
    out_firm = models.CharField(max_length=50, blank=True)
    out_qty = models.PositiveIntegerField(default=0)
    # message = models.TextField(null=True)
    message = models.CharField(max_length=300, blank=True, null=True)  # 수리의견


class ItemIn(models.Model):
    Item = models.ForeignKey(Item)
    in_date = models.DateField(default=date.today, help_text="입고일자")
    in_firm = models.CharField(max_length=50, blank=True)
    in_qty = models.PositiveIntegerField(default=0)
    # message = models.TextField(null=True)
    message = models.CharField(max_length=300, blank=True, null=True)  # 수리의견


class Stock(models.Model):
    Item = models.ForeignKey(Item)
    in_qty = models.PositiveIntegerField(default=0)
    out_qty = models.PositiveIntegerField(default=0)


class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

item/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song
from .models import RFId, RFIdDet, ItemIn, ItemOut


class RFIdForm(forms.ModelForm):

    class Meta:
        model = RFId
        fields = ['rf_id', 'mfr_date', 'mfr_firm']


class RFIdDetForm(forms.ModelForm):

    class Meta:
        model = RFIdDet
        fields = ['RFId', 'out_date', 'in_date']


class ItemOutForm(forms.ModelForm):
    class Meta:
        model = ItemOut
        fields = ['Item', 'out_date', 'out_firm', 'out_qty', 'message']


class ItemInForm(forms.ModelForm):
    class Meta:
        model = ItemIn
        fields = ['Item', 'in_date', 'in_firm', 'in_qty', 'message']


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

item/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.db.models import Q
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.template.engine import _context_instance_undefined
from django.template import RequestContext
from django.db import transaction, IntegrityError
from django.http import HttpResponse
from .forms import UserForm, RFIdForm, RFIdDetForm, ItemInForm, ItemOutForm
from .models import Album, Song
from .models import RFId, RFIdDet, Item, ItemIn, ItemOut
from datetime import datetime
from django.utils import formats

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def listRFId(request):
    rfids = RFId.objects.all()
    return render(request, 'item/rfid.html', {'rfids': rfids})


def item_in(request):
    if not request.user.is_authenticated():
        return render(request, 'item/login.html')
    else:
        if request.method == 'GET':
            if request.GET.get("op") == 'ADD':              # Data 입력폼
                form = ItemInForm(request.POST or None)
                context = {
                    'form': form,
                }
                return render(request, 'item/item_in1.html', context)
        else:
            form = ItemInForm(request.POST or None)
            if form.is_valid():                              # Data 저장
                item_id = request.POST.get('Item')
                item = get_object_or_404(Item, pk=item_id)
                obj = form.save(commit=False)
                obj.Item = item
                obj.save()
        # Data 조회화면
        itemins = ItemIn.objects.order_by('-pk')
        return render(request, 'item/item_in_list.html', {'itemins': itemins})


def item_out(request):
    if not request.user.is_authenticated():
        return render(request, 'item/login.html')
    else:
        if request.method == 'GET':
            if request.GET.get("op") == 'ADD':              # Data 입력폼
                form = ItemOutForm(request.POST or None)
                context = {
                    'form': form,
                }
                return render(request, 'item/item_out1.html', context)
        else:
            form = ItemOutForm(request.POST or None)
            if form.is_valid():                              # Data 저장
                item_id = request.POST.get('Item')
                item = get_object_or_404(Item, pk=item_id)
                obj = form.save(commit=False)
                obj.Item = item
                obj.save()
        # Data 조회화면
        itemouts = ItemOut.objects.order_by('-pk')
        return render(request, 'item/item_out_list.html', {'itemouts': itemouts})


def rfids_add(request):
    template_name = 'item/rfid_add1.html'
    if not request.user.is_authenticated():
        return render(request, 'item/login.html')
    else:
        error = False
        today = formats.date_format(datetime.now(), "Y-m-d")
        if request.method == 'POST':
            mfr_firm = request.POST.get('mfr_firm')
            mfr_date = request.POST.get('mfr_date')
            rfids = request.POST.get('rfids').strip()
            rfid_list = rfids.split('\r\n')

            i = 0
            try:
                with transaction.atomic():
                    for rfid in rfid_list:
                        i = i + 1
                        print("id='" + rfid + "'")
                        RFId.objects.create(rf_id=rfid, mfr_date=mfr_date, mfr_firm=mfr_firm)
                msg = "총" + str(i) + "건 성공했습니다."
                return render(request, template_name, {'error': error, 'message': msg, 'mfr_date': today})
            except IntegrityError:
                error = True
                msg = "RFID : '" + rfid + "'중복 데이타 입니다. "
                return render_to_response(template_name,
                                          {"error": error, "message": msg, 'mfr_firm': mfr_firm, 'mfr_date': mfr_date,
                                           'rfids': rfids, },
                                          context_instance=RequestContext(request))
        msg = "RFID를 여러개 등록할 수 있는 입력폼입니다."
        return render(request, template_name, {'error': error, 'message': msg, 'mfr_date': today})


# RFID 납품(출고)
def rfids_out(request):
    template_name = 'item/rfid_out1.html'
    if not request.user.is_authenticated():
        return render(request, 'item/login.html')
    else:
        error = False
        today = formats.date_format(datetime.now(), "Y-m-d")
        if request.method == 'POST':
            f_firm = request.POST.get('f_firm')
            f_date = request.POST.get('f_date')
            rfids = request.POST.get('rfids').strip()
            rfid_list = rfids.split('\r\n')

            i = 0
            try:
                with transaction.atomic():
                    for rfid in rfid_list:
                        i = i + 1
                        print("id='" + rfid + "'")
                        obj = RFId.objects.get(pk=rfid)
                        if obj.rf_id_state == 'OUT':
                            raise ValueError("RFID : '" + rfid + "'는 " + obj.rf_id_state +"상태로 출고대상이 아닙니다.")
                        obj.rf_id_state = 'OUT'
                        obj.out_firm = f_firm
                        obj.out_date = f_date
                        obj.save()

                        RFIdDet.objects.create(RFId=obj, out_date=f_date)
                    msg = "총" + str(i) + "건 성공했습니다."
                    return render(request, template_name, {'error': error, 'message': msg, 'f_date': today})
            except RFId.DoesNotExist:
                msg = "RFID : '" + rfid + "'가 존재하지 않습니다."
            except ValueError as e:
                msg = e.args
            error = True
            return render_to_response(template_name,
                                      {"error": error, "message": msg, 'f_firm': f_firm, 'f_date': f_date,
                                       'rfids': rfids, },
                                      context_instance=RequestContext(request))
        msg = "RFID를 여러개 등록할 수 있는 입력폼입니다."
        return render(request, template_name, {'error': error, 'message': msg, 'f_date': today})


# RFID 수리입고
def rfids_in(request):
    template_name = 'item/rfid_in1.html'
    if not request.user.is_authenticated():
        return render(request, 'item/login.html')
    else:
        error = False
        today = formats.date_format(datetime.now(), "Y-m-d")
        if request.method == 'POST':
            f_msg = request.POST.get('f_msg')
            f_date = request.POST.get('f_date')
            rfids = request.POST.get('rfids').strip()
            rfid_list = rfids.split('\r\n')

            i = 0
            try:
                with transaction.atomic():
                    for rfid in rfid_list:
                        i = i + 1
                        print("id='" + rfid + "'")
                        obj = RFId.objects.get(pk=rfid)
                        if obj.rf_id_state != 'OUT':
                            raise ValueError("RFID : '" + rfid + "'는 " + obj.rf_id_state +"상태로 출고되지 않은 제품입니다.")
                        # if obj.rf_id_state == 'OUT'
                        obj.rf_id_state = 'IN'
                        obj.in_date = f_date
                        obj.save()

                        det = RFIdDet.objects.filter(RFId=obj).last()
                        det.in_date = f_date
                        det.message = f_msg
                        det.save()
                        # print("--------------det  : " + str(det.count()))
                    msg = "총" + str(i) + "건 성공했습니다."
                    return render(request, template_name, {'error': error, 'message': msg, 'f_date': today})
            except RFId.DoesNotExist:
                error = True
                msg = "RFID : '" + rfid + "'가 존재하지 않습니다."
            except ValueError as e:
                msg = e.args
            error = True
            return render_to_response(template_name,
                                      {"error": error, "message": msg, 'f_msg': f_msg, 'f_date': f_date,
                                      'rfids': rfids, },
                                      context_instance=RequestContext(request))
        msg = "RFID를 여러개 등록할 수 있는 입력폼입니다."
        return render(request, template_name, {'error': error, 'message': msg, 'f_date': today})


def create_rfid(request):
    # print("create_album 111")
    # if True:
    #     return HttpResponse("create Album.....You're looking at question %s." % "question_id")

    if not request.user.is_authenticated():
        return render(request, 'item/login.html')
    else:
        form = RFIdForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            rfid = form.save(commit=False)
            rfid.save()
            return render(request, 'item/detail.html', {'rfid': rfid})
        context = {
            "form": form,
        }
        return render(request, 'item/create_album.html', context)


def create_rfiddet(request, rfid_rf_id):
    form = RFIdDetForm(request.POST or None, request.FILES or None)
    rfid = get_object_or_404(RFId, pk=rfid_rf_id)
    if form.is_valid():
        rfiddet = form.save(commit=False)
        rfiddet.RFId = rfid
        # rfiddet.rf_id_state = "납품"
        rfiddet.save()
        return render(request, 'item/detail.html', {'rfid': rfid})
    context = {
        'rfid': rfid,
        'form': form,
    }
    return render(request, 'item/create_song.html', context)


def delete_rfid(request, rfid_rf_id):
    rfid = RFId.objects.get(pk=rfid_rf_id)
    rfid.delete()
    rfids = RFId.objects.all()
    return render(request, 'item/index.html', {'rfids': rfids})


def delete_rfiddet(request, rfid_rf_id, rfiddet_id):
    rfid = get_object_or_404(RFId, pk=rfid_rf_id)

item/templates/item/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'item/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{%  static 'item/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'item/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'item/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">In&F Mananger v1.0</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'item:logout_user' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a class="{% block ITEM_IN1 %}{% endblock %}" href="{% url 'item:item_in' %}"><span class="glyphicon glyphicon-arrow-left"></span></i> 입고관리</a>
                        </li>
                        <li>
                            <a class="{% block ITEM_OUT1 %}{% endblock %}" href="{% url 'item:item_out' %}"><span class="glyphicon glyphicon-arrow-right"></span></i> 출고관리</a>
                        </li>
                        <li class="{% block RFID_MGMT %}{% endblock %}">
                            <a href="#"><i class="fa fa-files-o fa-fw"></i> RFID관리<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a class="{% block RFID_RET1 %}{% endblock %}" href="{% url 'item:index' %}">RFID 조회</a>
                                </li>
                                <li>
                                    <a class="{% block RFID_ADD1 %}{% endblock %}" href="{% url 'item:rfids_add' %}">RFID 등록</a>
                                </li>
                                <li>
                                    <a class="{% block RFID_OUT1 %}{% endblock %}" href="{% url 'item:rfids_out' %}">RFID 납품</a>
                                </li>
                                <li>
                                    <a class="{% block RFID_IN1 %}{% endblock %}" href="{% url 'item:rfids_in' %}">RFID 수리입고</a>
                                </li>
                            </ul>
                                <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

         <!-- Page Content -->
        {% block body %}
        {% endblock %}
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'item/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'item/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static '/static/item/vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- DataTables JavaScript -->
    <script src="/static/item/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/static/item/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/static/item/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'item/dist/js/sb-admin-2.js' %}"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>
</body>

</html>

item/templates/item/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'item/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'item/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'item:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'item:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'item:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

item/templates/item/create_album.html
{% extends 'item/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New RFID tag</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'item/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

item/templates/item/index.html
{% extends 'item/base.html' %}

{% block RFID_MGMT %}active{% endblock %}
{% block RFID_RET1 %}active{% endblock %}

{% block body %}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">RFID 관리</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- RFIDs -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>RFIDs
                </div>
                 {% if rfids %}
                    <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>RFID</th>
                                        <th>제조일자</th>
                                        <th>제조회사</th>
                                        <th>납품회사</th>
                                        <th>최종납품일자</th>
                                        <th>최종입고일자</th>
                                        <th>상태</th>
                                        <th>출고횟수</th>
                                        <th>삭제</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {%  for rfid in rfids %}
                                        <tr class="">
                                            <td><a href="{% url 'item:detail' rfid.rf_id %}" class="btn btn-primary btn-sm" role="button">{{ rfid.rf_id}}</a></td>
                                            <td>{{ rfid.mfr_date | date:"Y-m-d"}}</td>
                                            <td>{{ rfid.mfr_firm}}</td>
                                            <td>{{ rfid.out_firm}}</td>
                                            <td>{{ rfid.out_date | date:"Y-m-d"}}</td>
                                            <td>{{ rfid.in_date | date:"Y-m-d"}}</td>
                                            <td>{{ rfid.rf_id_state}}</td>
                                            <td>{{ rfid.rfiddet_set.count}}</td>
                                            <td>
                                                <a href="{% url 'item:delete_rfid' rfid.rf_id %}" class="btn btn-default btn-sm "><span class="glyphicon glyphicon-trash"></span></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                    </div>
                {% else %}
                    <div class="well">
                        <br>
                        <a href="{% url 'item:create_rfid' %}">
                            <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>&nbsp; Add an RFId</button>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

item/templates/item/login_origin.html
{% extends 'item/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'item:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'item:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}